server:
  port: 7251
  servlet:
    context-path: /core/product
  forward-headers-strategy: framework

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  application:
    name: product-service
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
  sql:
    init:
      mode: never
  cloud:
    openfeign:
      lazy-attributes-resolution: true
      client:
        config:
          default:
            logger-level: full
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 1000
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

logging:
  level:
    web: trace
    org.hibernate.orm.jdbc.bind: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true

springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-operation-id: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/core_product
    username: root
    password: 1234
  kafka:
    bootstrap-servers: localhost:29092

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7230/eureka

---
spring:
  config:
    activate:
      on-profile: stag
  datasource:
    url: jdbc:mysql://green-craze-mysql:3306/core_product
    username: root
    password: green-craze-be-v2
  kafka:
    bootstrap-servers: green-craze-kafka:29092

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://green-craze-eureka-service:7230/eureka

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://green-craze-mysql:3306/core_product
    username: root
    password: green-craze-be-v2

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://green-craze-eureka-service:7230/eureka
