server:
  port: 7253
  servlet:
    context-path: /core/user
  forward-headers-strategy: framework

spring:
  application:
    name: user-service
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
  sql:
    init:
      mode: never
  cloud:
    openfeign:
      lazy-attributes-resolution: true
      client:
        config:
          default:
            logger-level: full

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

logging:
  level:
    web: trace
    org.hibernate.orm.jdbc.bind: trace

eureka:
  instance:
    prefer-ip-address: false
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-operation-id: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/core_user
    username: root
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7230/eureka

---
spring:
  config:
    activate:
      on-profile: stag
  datasource:
    url: jdbc:mysql://localhost:3306/core_user
    username: root
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://green_craze-core-eureka-service:7230/eureka

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/core_user
    username: root
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://green_craze-core-eureka-service:7230/eureka
