server:
  port: 7252
  servlet:
    context-path: /core/order
  forward-headers-strategy: framework

spring:
  application:
    name: order-service
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
  sql:
    init:
      mode: never
  cloud:
    openfeign:
      lazy-attributes-resolution: true
      client:
        config:
          default:
            logger-level: full

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

logging:
  level:
    web: trace
    org.hibernate.orm.jdbc.bind: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true

rabbitmq:
  internal-exchange: internal.exchange
  mail-routing-key: mail.routing_key
  notification-routing-key: notification.routing_key

springdoc:
  use-fqn: true
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-operation-id: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/core_order
    username: root
    password: 1234
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7230/eureka

---
spring:
  config:
    activate:
      on-profile: stag
  datasource:
    url: jdbc:mysql://mysql-ebc761b-mantm040702-6005.a.aivencloud.com:24067/core_order
    username: avnadmin
    password: AVNS_ICGL1LOHUwComp9Dj2e
  rabbitmq:
    host: green-craze-rabbitmq
    port: 5672
    username: guest
    password: guest

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://green-craze-eureka-service:7230/eureka

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql-ebc761b-mantm040702-6005.a.aivencloud.com:24067/core_order
    username: avnadmin
    password: AVNS_ICGL1LOHUwComp9Dj2e
  rabbitmq:
    host: green-craze-rabbitmq
    port: 5672
    username: guest
    password: guest

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://green-craze-eureka-service:7230/eureka

