server:
  port: 7257
  servlet:
    context-path: /core/infrastructure

spring:
  application:
    name: infrastructure-service
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: cristran040702@gmail.com
    password: wxjugsquhiyajgdc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true
    test-connection: false
    protocol: smtp

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

logging:
  level:
    web: trace
    org.hibernate.orm.jdbc.bind: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true

rabbitmq:
  exchanges:
    direct: internal.exchange
  queues:
    mail: mail.queue
    notification: notification.queue
  routing-key:
    mail: mail.routing_key
    notification: notification.routing_key
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://mysql-ebc761b-mantm040702-6005.a.aivencloud.com:24067/core_infrastructure
    username: avnadmin
    password: AVNS_ICGL1LOHUwComp9Dj2e
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7230/eureka

---
spring:
  config:
    activate:
      on-profile: stag

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://green_craze-core-eureka-service:7230/eureka

---
spring:
  config:
    activate:
      on-profile: prod

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://green_craze-core-eureka-service:7230/eureka
