server:
  port: 7257
  servlet:
    context-path: /core/infrastructure

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  application:
    name: infrastructure-service
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: cristran040702@gmail.com
    password: wxjugsquhiyajgdc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true
    test-connection: false
    protocol: smtp
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true

logging:
  level:
    web: trace
    org.hibernate.orm.jdbc.bind: trace

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true

rabbitmq:
  exchanges:
    direct: internal.exchange
  queues:
    mail: mail.queue
    notification: notification.queue
  routing-key:
    mail: mail.routing_key
    notification: notification.routing_key
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/core_infrastructure
    username: root
    password: 1234
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: localhost:29092

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7230/eureka

---
spring:
  config:
    activate:
      on-profile: stag
  datasource:
    url: jdbc:mysql://mysql-ebc761b-mantm040702-6005.a.aivencloud.com:24067/core_infrastructure
    username: avnadmin
    password: AVNS_ICGL1LOHUwComp9Dj2e
  rabbitmq:
    host: green-craze-rabbitmq
    port: 5672
    username: guest
    password: guest

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://green-craze-eureka-service:7230/eureka

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql-ebc761b-mantm040702-6005.a.aivencloud.com:24067/core_infrastructure
    username: avnadmin
    password: AVNS_ICGL1LOHUwComp9Dj2e
  rabbitmq:
    host: green-craze-rabbitmq
    port: 5672
    username: guest
    password: guest

cloudinary:
  cloud-name: dwoejm4g6
  api-key: 531723158945791
  api-secret: vgCHOLFDpPoPe_DXyjk653ztW1k
  secure: true

eureka:
  client:
    service-url:
      defaultZone: http://green-craze-eureka-service:7230/eureka
